name: Main workflow

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Dependencies
      run: npm ci
    - name: Run eslint
      run: npm run lint
      
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Dependencies
      run: npm ci
    - name: Run unit test
      run: npm run test:unit
  
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [lint, test]
    env:
      VUE_APP_GA: ${{secrets.google_analytics_id}}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Dependencies
      run: npm ci
    - name: Build demo site
      run: npm run build
    - name: Upload demo site
      uses: actions/upload-artifact@v1
      with:
        name: demo-site
        path: dist
    - name: Build docs
      run: npm run docs:build
    - name: Upload docs
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: docs/.vuepress/dist

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    env:
      DEPLOY_TOKEN: ${{secrets.deploy_token}}
      USER_NAME: yoychen
      USER_EMAIL: yui12327@gmail.com
      PUBLISH_DIR: ./demo-site
    
    steps:
    - name: Download demo site
      uses: actions/download-artifact@v1
      with:
        name: demo-site
    - name: Download docs
      uses: actions/download-artifact@v1
      with:
        name: docs
    - name: Deploy demo site
      run: |
        mv docs $PUBLISH_DIR 
        cd $PUBLISH_DIR
        git init
        git config --local user.email $USER_EMAIL
        git config --local user.name $USER_NAME
        git remote add origin https://$DEPLOY_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git checkout -b gh-pages
        git add --all
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages -f
